---
title: "3rd Year Annual Review: Microbial communities performing dissimilatory nitrate reduction to ammonium in Australian forest soils"
author: "Eric Ireland"
date: "`r Sys.Date()`"
output: word_document
bibliography: PhD.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(citr)
library(readr)
library(officer)
library(flextable)
# chapters <- read_csv("chapters.csv", col_types = cols(.default = "c"))
# chapters <- read_csv("chapters.csv", col_types = cols(`No. of papers expected from chapter` = col_character(), 
#     `Progress on lab/field task (%)` = col_character(), 
#     `Progress on writing task (%)` = col_character()))
# chapters <- read_csv("chapters.csv")
chapters <- read_csv("chapters.csv", col_types = cols(chap.no = col_integer(), 
     progress.lab = col_integer(), 
     progress.writing = col_integer()))
```

This is a test [@ghaniHotwaterExtractableCarbon2003].

## test table

```{r chapter_table,echo=FALSE}

chapter_table <- flextable(chapters)
chapter_table <- theme_booktabs(chapter_table)
chapter_table <- merge_h_range(chapter_table, i = ~is.na(chap.no), j1 = "chap.description", j2 = "finish.date")
chapter_table <- bold(chapter_table, i = ~!is.na(chap.no))
chapter_table <- align( chapter_table, align = "center", part="header" )
chapter_table <- font(chapter_table, part="all", fontname = "Times")
chapter_table <- fontsize(chapter_table, part="all", size = 10)
chapter_table <- set_header_labels(chapter_table, chap.no="Chap. No.",
                                   chap.description="Chapter description",
                                   progress.lab="Progress on lab/field task (%)",
                                   progress.writing="Progress on writing task (%)",
                                   finish.date="Expected finish date")
chapter_table <- height_all(chapter_table, height = .3)
chapter_table <- width(chapter_table, j="chap.description", width = 3.5)
chapter_table <- width(chapter_table, j="chap.no", width = .6)
int_keys <- c("chap.no", "progress.lab", "progress.writing")
chapter_table <- colformat_int(x = chapter_table, col_keys = int_keys)
chapter_table <- set_caption(chapter_table, "Thesis and Research Plan.")
chapter_table

```

