---
title: "2018-07-24 Nanodrop results (Baw Baw)"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(kableExtra)
nanodrop <- read_tsv("nanodrop/2018-07-24_nanodrop_report.tsv", skip = 1,col_names = c("#","Sample ID","User name","Date and Time","Nucleic Acid Conc.","Unit","A260","A280","260/280","260/230",	"Sample Type","Factor"))# %>% 
#  select(`Sample ID`,`Nucleic Acid Conc.`, `260/280`, `260/230`)
```


```{r, echo=FALSE}
nanodrop %>%
  mutate(`260/280`=cell_spec(`260/280`,color = ifelse(`260/280`<1.8,"red","black")),
                    `260/230`=cell_spec(`260/230`,color = ifelse(`260/230`<1.8,"red","black")))  %>%
  select(`Sample ID`,`Nucleic Acid Conc.`, `260/280`, `260/230`,`Date and Time`,`Sample Type`) %>%
  rename(`Conc. (ng/µl)`= `Nucleic Acid Conc.`) %>%
  kable("latex", escape = F, booktabs = F) %>%
  kable_styling(latex_options = c("hold_position","striped")) %>% 
  column_spec(1, bold = T)
```

